// Generated by https://quicktype.io

export interface IResponse {
    status:  boolean;
    message: string;
    data:    IDataReponse;
}

export interface IDataReponse {
    total_albumes:   number;
    total_canciones: number;
    albumes:         string[];
    canciones:       ISong[];
}

export interface ISong {
    cancion_id:        number;
    nombre_album:      string;
    nombre_tema:       string;
    preview_url:       string;
    fecha_lanzamiento: string;
    precio:            IPrice;
    isFavorite?:       boolean;
}

export interface IPrice {
    moneda: string;
    valor:  string;
}
